display_name: PikaTorrent
publisher_display_name: G_Ray
identity_name: 19653GRay.PikaTorrent
publisher: CN=9FB02A40-50B6-49F9-92D4-AA9DC9AC1AAB
# protocol and file extensions handling are managed programmatically
# This is not perfect as registry entries will not be clean once the
# app is uninstall.
# protocol_activation: magnet
# file_extension: .torrent
capabilities: internetClientServer, privateNetworkClientServer
store: "true"
logo_path: ./windows/runner/resources/app_icon.ico
trim_logo: "false"